### ISSUE TITLE
May i know the exact version of Reicast on retro orange pi 4.2 slim?

### ISSUE THREAD

**Issue by ghost** [retr0rangepi/RetrOrangePi#56]
Hello how are you? for some reason your version of reicast is the only version that works flawlessly without any glitches on games like capcom vs snk 2, i'm in need to know which exactly version is this one so i can compile myself for my s905x board.

Would you please give me this information? 

Thank you so much, fantastic work you have been doing!

**Comment by retr0rangepi** [comment]
Binary version is circa July 2016. Source has changed a lot since then , so the headers and dependencies (SDL2, Mali, OpenGL ES etc). It's very hard to reproduce the same environment nowadays (Legacy 3.4.113 Debian Jessie vs Mainline 5.3.6 Ubuntu Bionic).

If you still want to give it a try, fetch sources from https://github.com/RetroPie/reicast-emulator.git (retropie branch), and use the following Makefile: http://www.retrorangepi.download/Makefile , 
Copy it into shell/linux and use make -j2 platform="odroid" to build it. Expect a lot of errors. Good luck.
