### ISSUE TITLE
Tritium H3 build for V4.3

### ISSUE THREAD

**Issue by keiem** [retr0rangepi/RetrOrangePi#59]
Hello

are there any plans to build retrorangepi 4.3 for the tritium H3.  Or can I just download any H3 version and change the DTB?

**Comment by retr0rangepi** [comment]
Please test: http://retrorangepi.download/RetrOrangePi_v4.3_Armbian_19.11.3_Tritium-h3_bionic_current_5.3.13_desktop.img.7z

**Comment by keiem** [comment]
Hello,

it doesn't boot
"found U-boot script /boot/boot.scr
Executing script at 43100000
Wrong image format for "source" command
SCRIPT FAILURE: continuing
card did not respond to voltage select

Device 0: unknown device_sun8i_emmc_eth_init: Timeout
missing environment variable:pxeuuid
missing environment variable: bootfile
..."

So according me it couldn't extract the kernel.

**Comment by retr0rangepi** [comment]
New image is up, same link. Please try again and post full log (picture)

**Comment by keiem** [comment]
Thanks, the image boots and everything seems to work.  Although I didn't test some games.  I can tell eduke32 wouldn't install and I can't seem to find super mario war in the optional packages.  Any reason why it is removed?

**Comment by retr0rangepi** [comment]
Thanks for the info. Since image works, i'm closing this one. 
Please open new issues to fix eduke32 and smw . The latter is not compatible with KMS  (new standard for mainline kernel) - https://github.com/retr0rangepi/RetroPie-Setup/blob/8996e64725fc30cafad56d58e52cc75b61333b56/scriptmodules/ports/smw.sh#L16
In previous versions, there was a hack using X11 desktop to run them, we'll have to check again.
